CXF 92626: Adding FCR 2 Metal connection Example
equinix/terraform-equinix-fabric pull request #79
Opened 2024-05-14 05:13 UTC by srushti-patl

- Added zside_ap_type = METAL_NETWORK in cloud-router connection sub module
- Added FCR 2 Metal Connection example
- Removed aside_ap_type variable from cloud-router-connection module and cloud router connectivity examples

2024-05-14 18:48 UTC, thogarty requested changes
I'm also confused about the port2Azure example value addition. Is there a variable for that and it was just omitted from the .tfvars.example file?

2024-05-14 18:48 UTC, thogarty commented on examples/cloud-router-2-metal-nimf-connection/versions.tf
> +      version = ">= 1.34.0"
Update version to v1.36.4. That's the version with the redundancy fix.

2024-05-16 17:34 UTC, srushti-patl commented
> I'm also confused about the port2Azure example value addition. Is there a variable for that and it was just omitted from the .tfvars.example file?

It was omitted from the tfvars.example file.
I have also added that variable to .tfvars.example file in the following examples:
Port-2-Azure-connection
Port-2-Azure-Redundant-connection
FCR-2-Azure-connection
FCr-2-Azure-Redundant-connection

2024-05-16 21:36 UTC, thogarty approved these changes
LGTM. Well done.

2024-05-16 21:42 UTC, merged